name: xtask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo xtask build --arch x86-64 --verbose
    - name: Run tests
      run: cargo xtask test --verbose

  build-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo xtask build --arch aarch64 --verbose
